# Generated by Django 5.1.6 on 2025-03-31 14:59

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_my_hw_bbcode_revrubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bboard.models.get_timestamp_path, verbose_name='фото')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фоты',
            },
        ),
        migrations.DeleteModel(
            name='My_hw_BBCODE',
        ),
    ]
